language: generic

sudo: required

addons:
    apt:
        packages:
            # All for coverage report
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - vim

script: TEST_DIR=$(pwd)/test VIMS=./vims ./test/test.sh

after_success: |
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz &&
    cd kcov-master &&
    mkdir build &&
    cd build &&
    cmake .. &&
    make &&
    sudo make install &&
    cd ../.. &&
    rm -rf kcov-master &&
    mkdir -p coverage &&
    TEST_DIR=$(pwd)/test VIMS=./vims kcov coverage ./test/test.sh &&
    bash <(curl -s https://codecov.io/bash)
