#!/bin/bash
# The argument fixes were supplied by John Kugelman
# https://stackoverflow.com/a/44745698/2689923
vim_cmds=()

PRINT_ALL=1
while (($# > 0)); do
    arg="$1"
    case "$arg" in
        -n|--no-print)
            PRINT_ALL=0
            ;;
        *)
            # unknown option
            vim_cmds+=(-c "$1")
            ;;
    esac
    shift
done

# Headless vim which exits after printing all lines
# Taken from Csaba Hoch:
# https://groups.google.com/forum/#!msg/vim_use/NfqbCdUkDb4/Ir0faiNaFZwJ
if [ "$PRINT_ALL" -eq "1" ]; then
    vim_cmds+=(-c ":%p")
fi

vim - -nes -u NONE "${vim_cmds[@]}" -c ':q!' | tail -n +2
