#!/bin/sh

PRINT_ALL=1
DISABLE_VIMRC=0
MODE=none

set -- "$@" '---vims-end---'
while :; do
    case "$1" in
        ---vims-end---) shift; break;;
        -n|--silent|--quiet) PRINT_ALL=0;;
        -d|--disable-vimrc)  DISABLE_VIMRC=1;;
        -e|--exe-mode)         MODE=exe;;
        -r|--inverse-exe-mode) MODE=inverse-exe;;
        -l|--line-exe-mode)    MODE=line-exe;;
        -s|--simple-mode)      MODE=simple;;
        -t|--turn-off-mode)    MODE=none;;
        *)
            case "$MODE" in
                none)        set -- "$@" -c "$1" ;;
                simple)      set -- "$@" -c ":exe \"norm gg""$1""\"";;
                line-exe)    set -- "$@" -c ":%g/.*/exe \"norm ""$1""\"";;
                exe)         set -- "$@" -c "%g/$1/exe \"norm $2\""; shift;;
                inverse-exe) set -- "$@" -c "%v/$1/exe \"norm $2\""; shift;;
            esac
            ;;
    esac
    shift
done

# Headless vim which exits after printing all lines
# Taken from Csaba Hoch:
# https://groups.google.com/forum/#!msg/vim_use/NfqbCdUkDb4/Ir0faiNaFZwJ
if [ "$PRINT_ALL" -eq "1" ]; then
    set -- "$@" -c ":%p"
fi
if [ "$DISABLE_VIMRC" -eq "1" ]; then
    set -- -u NONE "$@"
fi

vim - -nes "$@" -c ':q!' | tail -n +2
