name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        vim:
          - 'v9.0.2189'
          - 'v8.2.4286'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install coverage dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libelf-dev libdw-dev cmake kcov
      - uses: thinca/action-setup-vim@v1
        with:
          vim_version: ${{ matrix.vim }}
      - name: Ensure vim installed
        run: vim --version
      - name: Smoke test of vims
        run: echo "Hello" | ./vims ''
      - name: Run tests
        run: VIMS=$PWD/vims ./test/bats/bin/bats ./test/test.bats
