name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        vim:
          - 'v9.0.2189'
          - 'v8.2.4286'

    steps:
      - uses: actions/checkout@v4
      - name: Install coverage dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libelf-dev libdw-dev cmake kcov
      - uses: rhysd/action-setup-vim@v1
        with:
          version: ${{ matrix.vim }}
      - name: Run tests without coverage
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: |
          TEST_DIR=$(pwd)/test VIMS=./vims ./test/test.sh
      - name: Run tests with coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          mkdir -p coverage
          TEST_DIR=$(pwd)/test VIMS=./vims kcov coverage ./test/test.sh
      - name: Upload coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: bash <(curl -s https://codecov.io/bash) -s coverage
