name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libelf-dev libdw-dev cmake vim kcov
      - name: Run tests
        run: |
          mkdir -p coverage
          TEST_DIR=$(pwd)/test VIMS=./vims kcov coverage ./test/test.sh
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash) -s coverage


